SortedMethodsByCall/Waterfall:
  Description: "Enforces method ordering based on call relationships."
  Enabled: true
  VersionAdded: "1.2.1"
  SafeAutoCorrect: false
  AllowedRecursion: true
  SkipCyclicSiblingEdges: false
