name: CI

on:
  push:
    branches: [master]
    tags:
      - "v*"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # main test matrix (no fasterer)
          - ruby: '2.7'
            bundle_without: 'dev_tools'
          - ruby: '3.0'
            bundle_without: 'dev_tools'
          - ruby: '3.1'
            bundle_without: 'dev_tools'
          - ruby: '3.2'
            bundle_without: 'dev_tools'
          - ruby: '3.3'
            bundle_without: 'dev_tools'
          - ruby: '3.4'
            bundle_without: 'dev_tools'
          - ruby: '4.0'
            bundle_without: 'dev_tools'

    env:
      BUNDLE_WITHOUT: ${{ matrix.bundle_without }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: RuboCop (selfâ€‘check)
        run: |
          bundle exec rubocop
          bundle exec rubocop --config test_project/.rubocop.test.yml lib/ -A

      - name: RSpec
        run: bundle exec rspec

  dev_tools:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby 3.4
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true

      - name: Fasterer
        env:
          BUNDLE_WITHOUT: ''  # install dev_tools here
        run: |
          bundle install
          bundle exec fasterer

  release:
    needs: [test]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
      - name: Build gem
        run: |
          gem build rubocop-sorted_methods_by_call.gemspec
          test -f rubocop-sorted_methods_by_call-*.gem
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: rubocop-sorted_methods_by_call-*.gem
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push gem to RubyGems.org
        env:
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        run: gem push rubocop-sorted_methods_by_call-*.gem
